name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      # Install NPM dependencies, cache them correctly
      - name: Install Dependencies
        run: npm install
        
      # Build the project and ignore TypeScript errors
      - name: Build project
        run: tsc --noEmit --skipLibCheck || true
        
       # Start the application and run Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm start
