name: Cypress Tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # - name: Set up Node.js
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Cache Node Modules
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

        # Start the application and wait until it's fully loaded
    - name: Start and wait for the frontend to be ready
      run: |
        npm start &  # Start the app in the background
        npx wait-on http://localhost:3000 # Wait until the frontend is fully loaded on port 3000
      env:
        REACT_APP_API_URL: https://tm-backend-16bm.onrender.com

    # Run Cypress tests
    - name: Cypress run
      uses: cypress-io/github-action@v6
      with:
        config: baseUrl=http://localhost:3000


    - name: Archive Cypress test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: cypress-results
        path: cypress/results


    container:
      image: cypress/included
